### ISSUE TITLE
[1.18][Crash]: 

### ISSUE THREAD

**Issue by BrandonApproved** [CorgiTaco/BYG#1037]
### BYG Version

1.18.2-1.4.7

### Terrablender Version

1.18.2-1.2.0.126

### Mod Loader

Forge

### Mod Loader Version

40.1.80

### What happened?

1. Created a new world
2. loading screen gets stuck at 0%

The game does not actually crash but freezes. I had to force quit the game in task manager to get the crash log.

### crash-log

[crash-2022-12-17_17.04.16-server.txt](https://github.com/AOCAWOL/BYG/files/10252953/crash-2022-12-17_17.04.16-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10252955/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by BrandonApproved** [comment]
Tried BYG by itself and the world generates fine.

**Comment by CorgiTaco** [comment]
Make sure you're using the latest BYG & Terrablender available for the current MC version you're playing. Otherwise if you have done so already... there is a conflict with one or several mods that add biome features so you'll need to figure out which mod is causing the conflict. Otherwise closing this as a mod conflict.
