### ISSUE TITLE
[1.19][Bug]: Blueberries not being generated

### ISSUE THREAD

**Issue by JalapenoGremlin** [CorgiTaco/BYG#1072]
### BYG Version

1.19.2-2.0.0.13

### Terrablender Version

1.19.2-2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### Bug Severity

Major

### What happened?

Every world I generate, does not seem to create blueberry bushes in any biome. After perusing the code I looked in sever seeds in the following biomes and have never found a single blueberry bush: 

- blackForest
- daciteRidges
- daciteShore
- temperateRainForest
- canadianShield
- coniferousForest
- frostedTaiga
- autumnalTaiga
- twilightMeadow

### latest.log

<script src="https://gist.github.com/JalapenoGremlin/44bd8fcd50bdd54936a2de49a6568738.js"></script>

### Did you isolate BYG?

I tried BYG alone

**Comment by JalapenoGremlin** [comment]
Doh! This log is for the fabric loader. I tried BYG in both Fabric and Forge but had the same issue in both. (I originally had BYG and Ars Nouveau, but thought that maybe the source bushes from Ars Nouveau were replacing byg:blue berry bushes, but that doesn't seem to be the case).

**Comment by AOCAWOL** [comment]
Blueberries do inconsisently spawn at extremely unintended rates. I have adjusted this so that blueberries in our next update will spawn much more common. I have also redone the biomes blueberries spawn in:

The following Biomes Will Spawn Blueberries Now:
Zelkova Forest
Weeping Witch Forest
Howling Peaks
Autumnal Taiga
Rose Fields
Coconino Meadows
Maple Taiga
Dacite Ridges
Coniferous Forest
Cika Woods
Canadian Shield
Black Forest

**Comment by JaboyKoral** [comment]
Would like to echo this same anomaly for 1.18.2 as well, in case it hasn't already been noted.
