### ISSUE TITLE
[1.19][Crash]: 1.19.2 Fabric Server Keeps Crashing On Start

### ISSUE THREAD

**Issue by danolhenl** [CorgiTaco/BYG#1122]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.130

### Mod Loader

Fabric

### Mod Loader Version

0.14.17

### What happened?

I've been trying to get this server but I keep running into issues. The latest one is a weird crash that doesn't seem to give any description; it just says "Minecraft has crashed!". Not sure if BYG is the mod that is causing the issue, but I figure I'll start here. I'm using Terralith, Oh The Biomes You'll Go, Corgilib, Geckolib, Terrablender, and Create. I tried BYG alone with it's dependencies and had the same issue. Thanks! 

### crash-log

refer to latest.log

### latest.log

https://gist.github.com/danolhenl/539c36313ac29aeb916823987ab3fa40#file-latest-log

### Did you isolate BYG?

I tried BYG alone

**Comment by danolhenl** [comment]
It's worth noting that I also have tried booting up Minecraft on my computer using the same mods as well as just BYG and it's dependencies, and get the same log with an exit code 1.

**Comment by SpiffyDragon13** [comment]
I am having this exact same problem and it is definitely being caused by either Terrablender or BYG, I removed all mods when I began getting this same error, and started adding them back bit by bit and it was right after I re-added these mods. Attaching the relevant log[
[latest.log](https://github.com/AOCAWOL/BYG/files/11043125/latest.log)
](url)

**Comment by itsdinkd** [comment]
You are missing GeckoLib. it is not in your modlist

**Comment by CorgiTaco** [comment]
You'll need to add Geckolib.
