### ISSUE TITLE
[1.19.2][Crash]: 

### ISSUE THREAD

**Issue by crazybre02** [CorgiTaco/BYG#1229]
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.166

### Mod Loader

Forge

### Mod Loader Version

43.2.21

### What happened?

I tried to load up the game but it doesent even get to launching minecraft then it gives me minecraft error code: 1 ive cleared the config files. ive put it by itself. its the most recent i could download. im not sure what else to do. and i look in the crash logs folder and it doesent even give me one!

### crash-log

it doesent give me a crash log

### latest.log

‹      ÿ­”mkÛ0Çßún¬Ð
jÕ²çQÈ2Útäa,)e„¾P­kl*KF’ãe/öÙ''iF::Ò-Ø/ÎÖÝÿ§;næûú¥w0¡µK¨„	è‰¥…ë1¼¥ç×£Ë±[—hIžIL4{°$Yyy™‘«2aÕK™½ëÀ¬×ïNïàCO³Ëýà¾!Í6¨àà¨Ï(åòúYêžŸ[­“š ^ ›jdüI~2ý4¾™Ö
‰Ê‰IRYjÙ1ø=WœÜû'¬#X~ÏÙ‰’C4†ÍñÄïxÔÅXX(m39‡B°¥S¿o4c}ê5cê{QŒÔcmÚò¢GØ~`Aè`¼óZ-Ò¦~ÔŠ"JÛÍ¸Ñ<ƒ¸AšqÐ8ƒ¶mF~Üj‡aàÖÞoS	Â—RÙ­”Y¹LZœkf‘“ë­¹w	LØ¢Þ;“
VšÚž³	!ÿÊ>ýxÎHÒR>xP.PÀ©;=¸UZðÓså\«ÚüaÓÃnb‹­V…C¾Ùû¯6’°ö8 ðº8ëæ1×]Õôð²¯=ËÆKØËáÀ©ÞH¡¯…y–£4™’àïÝ-
±¬ƒS%¸óJ=–…Ù;¾¿ÌÉeølóû7"+y¦ÈD•’™t³bU¶ús²4s0iiWƒ«Jî\´?A·Ý¯£Wº¥M•îÀV
¸©uUUw·…IGâ†ÜñÑ/›à%ê  
[2023-07-24-52.log.gz](https://github.com/AOCAWOL/BYG/files/12156132/2023-07-24-52.log.gz)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by 191419141914** [comment]
Hola, me pasa exactamente lo mismo ¿alguien ha encontrado alguna solucion?

**Comment by sjb8227** [comment]
this is one of my fav biome mods and this happens every time. I updated forge, terra blender, everything and it always does this, has anyone found a solution?

**Comment by Pepperaldoli** [comment]
Hi I have the same problem, though my log crash says that is due byg for trader trying to sell mangrove_sapling and that's still in experimental. This lending me to de trade.json5 file in which i tried to erase it or change it but apparently works but when i try to make a new world or enter any other de minecraft crashes. So, so far I don't find the real way to solve it.
Also I tried with the  2.0.1.4 BYG version but also the 20.0.0.10, 20.0.0.13 with the terra blender version 2.0.1.136
I hope someone can give us an answer or a configuration to use on the 1.19.2 forge because is in my opinion the best biome mod for minecraft on every version or at least one of the best.

Hola espero que cualquiera lea inglés pero si sólo lees español pues en resumidas cuentas no carga bien por el mod por una pequeña configuración aparente del byg en el trade.json5 para el mangrove_sapling, arriba pongo las versiones que probé para el BYG con el terra blender.
Espero que alguien nos pueda dar una respuesta para disfrutar de este mod de biomas tan padre. Una configuración o algo para poder usarlo.

**Comment by JT122406** [comment]
Delete the file and regen
