### ISSUE TITLE
[1.19][Bug]: Therium Lamp Recipe Bugged

### ISSUE THREAD

**Issue by KellenLuce** [CorgiTaco/BYG#1237]
### BYG Version

4.0.0.2

### Terrablender Version

2.2.0.154

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### Bug Severity

Minor

### What happened?

Therium Lamps seem to have the same recipe as Therium Lanterns, and are therefore uncraftable in survival mode. 

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/12306065/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by GamingWithDudeAlt** [comment]
This is something that can be fixed by using the Polymorph mod. It basically makes it so if 2 or more items have the same recipe, you can choose between the item you want, and all of the other items that use that recipe. It's really helpful in big modpacks, and it's aswell available for both forge and fabric, but the BYG devs themselves should probably fix this issue.
