### ISSUE TITLE
[Minor Bug] Soapstone Tile Slabs don't drop their item when broken 

### ISSUE THREAD

**Issue by throckmorpheus** [CorgiTaco/BYG#155]

**Comment by CorgiTaco** [comment]
Could you please specify information provided from the issue template thank you.

**Comment by John-M87** [comment]
I also have the same issue with Dacite slabs.

Specifically when broken with a diamond pickaxe, but I haven't really tried anything else out

**Comment by tariqk** [comment]
__**Mod conflict? If so, please clarify which mod is conflicting!**__
Unlikely. But for completeness sake, the version of [All of Fabric 3](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3) I am using apparently uses BYG version 1.1.2.

__**API/Modloader**__
Fabric

__**Describe the bug**__
Soapstone brick slabs are un-harvestable using pickaxes. Using Hwyla, the effective tool is shovels.

__**To Reproduce**__
1. Obtain soapstone.
2. Use a stonecutter to produce soapstone brick blocks, which are harvestable with pickaxes
3. Use a stonecutter to produce soapstone brick slabs using soapstone brick blocks.
4. Place soapstone brick slab anywhere. Attempt to harvest soapstone brick slab with pickaxes, ranging from stone, iron to diamond.

**Expected behavior**
By rights, like it's originating block, soapstone brick slabs should be harverstable using pickaxes instead of shovels.

**Screenshots/Videos**

![2020-11-10_00 59 28](https://user-images.githubusercontent.com/3965641/98574227-a45e3700-22f2-11eb-9ca4-1d0fc05a70b2.png)


**Additional context**
As stated above, I'm using All of Fabric 3, version 2.3.4, The BYG version used in AOF3 appears to be 1.1.2.

**Logs**
None applicable.

**Comment by AOCAWOL** [comment]
fixed issues were it had shovel as it's harvest tool
