### ISSUE TITLE
Gen data Failures

### ISSUE THREAD

**Issue by Moleculor** [CorgiTaco/BYG#194]
__**Mod conflict? If so, please clarify which mod is conflicting!**__
BYG v1.1.5
Quark-r2.4-279

__**API/Modloader**__
Forge

__**Describe the bug**__
`/gendata` does not generate JSON files. It generates the `pack.mcmeta` file and the full directory structure (e.g. `D:\MultiMC\instances\1.16.41\.minecraft\saves\New Worldfasdsdfafsdaasfd\datapacks\gendata\byg-custom\data\byg\worldgen\biome`), but the directory where the JSON files should be is, instead, empty.

__**To Reproduce**__
Install Minecraft, Forge 35.1.13, BYG v1.1.5, Quark-r2.4-279 and its necessary library, AutoRegLib-1.6-47. 
Launch this collection.
Create a new world.
Type `/gendata byg` in to chat. 
Type `/gendata minecraft` in to chat.
Click on both provided links. 
Observe the deepest folder created in these directory structures are empty.

**Expected behavior**
JSONs for all the biomes should be there, instead of an empty directory.

**Logs**
https://gist.github.com/Moleculor/d9c5454c59c6c319badaf7536335b9a3

**Comment by Moleculor** [comment]
It was pointed out on Discord that Quark has a Realistic World generation option. I wasn't *consciously* using it, but it was flagged as 'true' in Quark's config UI. 

Considering Quark Realistic is actually a World Type listed in the world generation options when first creating the world (that I did not go out of my way to select), and when the config option was flagged as True, the worlds that were being generated still looked pretty Minecrafty, I doubt it was actually running? Especially since Default is still what it seems to default to even with the config option set to True.

But I disabled the option in Quark's UI, made sure I was using 'Default' as the World Type, and still no JSONs were generated. 

(I also tried turning it back on and generating a Quark Realistic World Type, which looked decidedly different than what I was getting in previous tests, and also no JSONs, but that's not surprising. I *also* went through Quark's config UI and disabled every single last thing listed that I could find. Generated a standard Default World Type. Still no JSONs. Don't know if that helps, but figured I'd mention it.)

**Comment by AgentStormy44** [comment]
I'm not sure whether or not this is the same issue, but when both Quark and BYG are installed, I will have various crashes that occur when loading up my modpack. Opening the pack several times will eventually let me play the pack, so until now I have been ignoring it. However, I have been noticing some fairly odd behavior with the game, such as more and more biomes being incorrectly listed after each start. For example, in the nether, the glowstone_gardens biome exists, however this for some reason was put into the overworld in a rose field I once passed through, causing the area to start spawning piglins and ghasts. This issue also seems to cause changes to the nether much more frequently, such as the biome tropical_islands being shown in biomes in the nether, along with white_beach as well. This causes overworld hostile creatures such as zombies and creepers to start appearing rather than the usual piglins.

(https://user-images.githubusercontent.com/76975760/103604698-e1ecd400-4edf-11eb-83af-bbca43a1b001.png)

(https://user-images.githubusercontent.com/76975760/103604737-faf58500-4edf-11eb-9d45-97b1ffccdd0b.png)

(https://user-images.githubusercontent.com/76975760/103604753-021c9300-4ee0-11eb-9b46-aec32c8656e8.png)

(https://user-images.githubusercontent.com/76975760/103604762-08127400-4ee0-11eb-9c51-4a25423e1d93.png)

All of the above are screenshots of what these errors look like and are causing. Considering its these two mods that always crash every once in a while, and doing some looking in on github led to me finding this bug report, I believe this may help with the issue.

**Comment by CorgiTaco** [comment]
@AgentStormy44 Let's say....
The biome mods I have installed are BYG(Numerical ID's are 100 - 125), BOP(126 - 155), and Prehistoric Fauna(156 - 207).
I create a new world. the biome at 0, 0 is a PHF Hell's Creek.
Only the Biome numerical ID is saved to the chunk so... PHF Hell's Creek in this case is 157.
So biome numerical ID 157 is stored at 0, 0.
Alright... BYG just got an update and they added 3 new biomes. So what happens? Well....
The biome mods I have installed are now BYG(Numerical ID's are 100 - 128), BOP(129 - 158), and Prehistoric Fauna(159 - 210).
So now the biome at 0, 0 still has the numerical ID 157 but.... the ID's have shifted, now the biome at 0, 0 is a Biomes O Plenty Alps Biome.

I recommend that you use the latest version of your modloader as the issue has been fixed for sure.
Forge: http://files.minecraftforge.net/ or if that doesn't work, https://www.curseforge.com/minecraft/mc-mods/chocolate-fix/files
Fabric: https://fabricmc.net/use/ & https://www.curseforge.com/minecraft/mc-mods/fabric-api/files

**Comment by CorgiTaco** [comment]
So what's gonna happen I think... is we'll be pointing at the World Gen Registries instead and this should avoid this issue altogether. Getting the datapack info from the LIVE datapack registry is a waste tbh. Using world gen registries is almost always guaranteed to work whereas datapack registries are basically held together with scotch tape
