### ISSUE TITLE
[1.16.4] Glowcane not spawning.

### ISSUE THREAD

**Issue by Yamza** [CorgiTaco/BYG#242]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**

__**Mod conflict? If so, please clarify which mod is conflicting!**__
Doesn't seem to be, tested with BYG and Natures Compass only.

__**API/Modloader**__
Forge

__**Describe the bug**__
Glowcane does not spawn in Glowshroom Bayou

__**To Reproduce**__
Explore a Glowshroom Bayou.

**Expected behavior**
Glowcane should be spawned.

**Screenshots/Videos**
Explored the entirety of this biome to find none.
https://i.imgur.com/hzNqSLf.png

**Additional context**
byg-1.1.7-BETA-v1.jar

**Logs**

**Comment by Thiana** [comment]
I've also not been able to find these in the biomes they are supposed to spawn in. Using byg-1.1.7-BETA-v2 with Enigmatica 6/dev

**Comment by Thiana** [comment]
After I was unable to find these, I decided to cheat some in so I could use them in a build but it turns out they cant be placed in world. I tried on sand/grass both with and without water adjacent. I'm not sure if you want a separate issue opened for this or if the problem is linked to the spawning issue?
