### ISSUE TITLE
MC Server crashes due to BYG

### ISSUE THREAD

**Issue by Username-Is-Unavailabl** [CorgiTaco/BYG#284]
When i start up a server, I get this error: https://pastebin.com/RCg1NLun

Also, I have 178 mods and some of them might be conflicting with byg (for example, i have young's better mineshafts and better caves, i also have better end, better nether, better weather, starlight)

All the 178 mods worked together fine  in the minecraft client, but when i try to use them on the server i get that error.

I really don't know what i can do about this and your help is really appreciated!

**Comment by saltyseadoggo** [comment]
Looking through the error report: do you have Hydrogen installed? Because, if you do, Hydrogen does not get along with BetterNether or Better End, which you listed above (see [this issue](https://github.com/CaffeineMC/hydrogen-fabric/issues/19)), and causes crashes.

Aside from that, I also found that 'ViaFabric' and 'Fabric Registry Sync' appear to be conflicting...
` - Mod 'ViaFabric' (viafabric) conflicts with any version of mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0), but a matching version is present: 0.7.4+ca58154a7d!
         - While this won't prevent you from starting the game, the developer(s) of 'ViaFabric' (viafabric) have found that version 0.7.4+ca58154a7d of 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) conflicts with their mod.
         - It is heavily recommended to remove one of the mods.`

... and 'ViaBackwards' appears to be missing a dependancy, 'viarewind.'
` - Mod 'ViaBackwards' (viabackwards) recommends any version of mod viarewind, which is missing!
         - You must install any version of viarewind.`
         
I'd suggest trying removing Hydrogen, followed by removing one of the two conflicting mods, and adding 'viarewind' to the pack if you keep ViaBackwards. I'm no genius about this stuff, but see if any of those help.

**Comment by Username-Is-Unavailabl** [comment]
1.I removed hydrogen and now the server works. 
2.How can ViaFabric conflict with Fabric Registry Sync, since the latter is not even a mod and I can't do anything about it.
3.I didn't know ViaRewind was needed for ViaBackwards, i will add it to the pack.
Thanks for the help!
