### ISSUE TITLE
Nether rendering

### ISSUE THREAD

**Issue by KacperBalcerowski** [CorgiTaco/BYG#303]
Nether doesn't render when playing on server. 
Version 1.16.4 forge-35.1.36 
Mod version: 1.1.8
I play about 120 mods but without any nether mods, a piece of the world sometimes appears while flying.
Can I somehow disable the mod's nether?

![Bez tytułu](https://user-images.githubusercontent.com/49233306/107894407-e15c4a00-6f2f-11eb-8e0a-f43b0ee7a2b7.png)

**Comment by CorgiTaco** [comment]
this issue is resolved in latest. If you want to disable our nether in an existing world, you must edit the level.dat for your world.

And please follow this rule that is explicitly stated in the Bug Major Issue template next time: **1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
