### ISSUE TITLE
Wandering Trader integration

### ISSUE THREAD

**Issue by saltyseadoggo** [CorgiTaco/BYG#337]
**Is your feature request related to a problem? Please describe.**
BYG adds an astoundingly wide variety of new plants, trees and decorational blocks, which is lovely! However, these are spread across so many biomes that it can be difficult to find one in particular for a build. If you absolutely need a particular wood type, a particular colour of sand, reeds for thatch or a particular flower for your flowerbed, you may need to go a very long way to find them- longer than in vanilla due to the wider biome pool! Before writing this up, I was just informed in my and my partner's survival world by the Biome Locator mod that the nearest weeping witch forest is over six thousand blocks away from our home, for example. This is to say nothing of finding a given biome without the help of /locatebiome or a mod like Biome Locator!

**Describe the solution you'd like**
Vanilla has its own solution for this problem: the wandering trader, which sells every variety of sapling and flower, as well as other plants like ferns, coral blocks, sea pickles or kelp, and even normal and red sand. I think it would be just lovely if BYG added trades to the wandering trader's possible trades list for all of its saplings, flowers, sand colours and other plants, so that, with some RNG, players can obtain some resources from far-away biomes.
This would also make BYG feel a little bit more integrated into vanilla. No biome mods that I've seen on the Fabric side of things even bother with the wandering trader, which leaves them and their vanilla trades feeling a little bit out of place.

**Describe alternatives you've considered**
- Using the Biome Locator mod or similar mods, or enabling cheats to use the vanilla /locatebiome command. This solution doesn't replace those, as one will still need to eventually make an enormous trek to the nearest located biome for its resources, but it can help offset that by granting the player some of these resources at the comfort of their home.
- Cheating in the resources, which I would rather not do due to disliking cheating.

**Additional context**
The wandering trader's vanilla sales: https://minecraft.gamepedia.com/Trading#Java_Edition_sales

**Comment by HappyCuppy** [comment]
I'm adding what I think is an improvment to your suggestion, with I absolutely think is great: "travelling traders" these are _not_ like existing wandering traders. 
Imagine in real life that there are wandering traders - and there have been wandering tribes throughout history. Those wandering traders just went around from one area to the next, and "collecting" whatever's was in their way, and in vanilla Minecraft it kind of looks like that, too - wandering traders don't really have related items. Travelling trades would - imagine someone coming from one area - which in BYG would be a biome, or _maybe_ a set of biomes, and will carry items from that specific biomes.

Imagine ancient empires or civilizations that made contact with far-away ones - they established trade routes, and traded with with one another their local goods for the other one's local goods. That's what I think would absolutely great to have implemented - rather than having **only** the ability to get **random** items from all biomes - which there are a TON in BYG - moreover, the more biomes that there are, the smaller the chance you have to get the item(s) you want - especially if you want to build something from a specific theme (e.g you established a base in a beachy biomes but want to make a house from evergreen logs, and decorate with dark green colored leaves - those are colors you don't see in your beachy biome). Another example is food you can't get in your area, etc.

**Comment by AOCAWOL** [comment]
This has been added :)
