### ISSUE TITLE
Nether Biomes Spawn weights

### ISSUE THREAD

**Issue by Nebula240** [CorgiTaco/BYG#341]
**Is your feature request related to a problem? Please describe.**
I noticed that some of the Biomes in the Nether are SO repetitive, ie: The Wither Forest, I had to walk in a straight line for 4000 blocks just to find the nether wastes. While in the journey I found the same biome 8 times.

**Describe the solution you'd like**
Please add the config for us to add Nether Biomes chances.

**Describe alternatives you've considered**
Commiting not alive.

**Additional context**

**Comment by TelepathicGrunt** [comment]
Nether biome weights isn’t a thing really if it’s using the vanilla system. It’s biome parameter distance to the noise value that determines what biome spawns. It might be that Wither Forest’s parameters needs to be adjusted so that it isn’t so close to what the average noise value is. It takes a lot of experimenting to get it right but it definitely isn’t something easily configurable for end users

**Comment by CorgiTaco** [comment]
Going to close this as the format of config files has vastly changed. But in current versions they should have weights
