### ISSUE TITLE
Pollen blocks emit light?

### ISSUE THREAD

**Issue by K0-RR** [CorgiTaco/BYG#411]
I find this weird so I'm asking if this is intentional and why. Value seems to be 9.
![image](https://user-images.githubusercontent.com/43277609/114298854-a5211200-9ab8-11eb-8eaa-196d48ccf524.png)

**Comment by MarioSMB** [comment]
This is very likely intentional, however I agree that it is quite weird and may look much better without light.  
As a side note, maple trees in real life are beautiful and offer so much potential for breathtaking scenery in this game, so I hope some adjustments can be made to the tree itself when addressing their pollen.

**Comment by AOCAWOL** [comment]
WIll be adjusted in a future update but it is intended
