### ISSUE TITLE
[Suggestion] Berry Good compatibility: blueberry pips

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/BYG#420]
**Is your feature request related to a problem? Please describe.**
Blueberries face the same issue as vanilla sweet berries in that they're awkward to use as a food source, being planted while trying to eat them. The Berry Good mod aims to fix that, but does not natively provide support for this mod's berries

**Describe the solution you'd like**
Please add a blueberry pips item when Berry Good is installed: https://github.com/team-abnormals/berry-good/issues/17

**Describe alternatives you've considered**

**Additional context**

**Comment by CorgiTaco** [comment]
We will not being arrangements for specific mods. If they don't want to support it that's on them not us. It's not difficult to do if checks for mods that change vanilla standard. I see in their issue report they said it's on us to do when quite frankly it isn't since their own mod changes the vanilla standard on berries. If we ever do add pies it'll be in Byg in general not something exclusive to their mod when both our mods are present

**Comment by CorgiTaco** [comment]
Feel free to open another issue suggesting blue berry pies if you'd like tho as I like the idea :)

**Comment by MarioSMB** [comment]
They are also unwilling, and their reasoning makes more sense to me. Could you please reconsider solving this incompatibility on your side?

**Comment by CorgiTaco** [comment]
regardless it's getting added in our own mod

**Comment by Mugman2000** [comment]
Not to necropost or anything, but will a config be added when you add this? I personally play with Berry Good and like this feature, but I imagine someone somewhere won't like it.
