### ISSUE TITLE
Unknown dimension:-1 without optifine

### ISSUE THREAD

**Issue by cepnisabann** [CorgiTaco/BYG#508]
[latest.log](https://github.com/CorgiTaco/BYG/files/6586380/latest.log)
byg makes server lag sometimes it causes freeze so that i have to full restart server

**Comment by jeremiahwinsley** [comment]
We are getting the same issue on a server, but we are getting watchdog crashes due to a mod conflict. 
Some mod sets IS_RUNNING_IN_IDE to true, which pauses the server until the watchdog kills it. 
Given that IS_RUNNING_IN_IDE is a non-final vanilla field, it doesn't seem safe to rely on this always being false in a release build.

This is from ATM6 1.7.2, but the original error itself happens with just BYG 1.2.9. https://gist.github.com/jeremiahwinsley/309b05701f634cb1fffcd4b435d1df57

**Comment by CorgiTaco** [comment]
This should be fixed in latest
