### ISSUE TITLE
Falling leaves from all trees added with this mod 1.17 fabric

### ISSUE THREAD

**Issue by JonCaver** [CorgiTaco/BYG#524]
**Before filling out this issue: **
**1. We only support the latest version of BYG on for Minor Bugs.**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict.**
Tested on 1.17 (latest version)
Tested with only BYG running
tested on latest version of mod available on Curseforge
__**Mod conflict? If so, please clarify which mod is conflicting!**__
No other mods

__**API/Modloader**__
Forge/Fabric?
Fabric
__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
When ever your character gets close to trees the leaves with fall off the outer parts of tree causing leaf blocks to pile up all over the ground. not only does this take away from the intended shape and design of the trees but it does create lag if enough leaf blocks are in the area.  If you walk a bit you can see the trees spawn into the world as normal but as you get closer the tree canopy will start to shrink and when you get next to the tree there will be leaf blocks all over the ground around the tree.
__**To Reproduce**__
Provide step by step instructions
loading a new world and traveling to any BYG biome with trees
**Expected behavior**
For the leaves to stay on the tree in the design that was intended for each tree. Also why the leaf blocks fall intact and not despawn when not attacked to the tree? As if you were using sheers or silk touch on them.
**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem. 

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log -

**Comment by delwest** [comment]
Thanks for this mod!! I'm seeing the same set of issues here, using only BYG 1.1.8-BETA with Fabric API 0.36.0 for 1.17, seems to be a few different things going on:
1. When walking into a BYG biome, leaves will randomly decay, even if touching a wood block. It happens with vanilla or modded leaves, but with all trees created by BYG (ie vanilla oak leaves on a tree spawned by BYG, still have this issue. Vanilla trees or trees from other mods don't seem to have the issue).
2. When specifically BYG-added leaves decay, or are broken by hand/non-Silk-Touch tool, etc, they drop one corresponding leaf block per block broken, instead of dropping a random number of saplings/twigs.

**Comment by delwest** [comment]
> Thanks for this mod!! I'm seeing the same set of issues here, using only BYG 1.1.8-BETA with Fabric API 0.36.0 for 1.17, seems to be a few different things going on:
> 
>     1. When walking into a BYG biome, leaves will randomly decay, even if touching a wood block. It happens with vanilla or modded leaves, but with all trees created by BYG (ie vanilla oak leaves on a tree spawned by BYG, still have this issue. Vanilla trees or trees from other mods don't seem to have the issue).
> 
>     2. When specifically BYG-added leaves decay, or are broken by hand/non-Silk-Touch tool, etc, they drop one corresponding leaf block per block broken, instead of dropping a random number of saplings/twigs.

Oops and forgot to say, same non-silk-Touch issue applies to several BYG grasses, such as short grass and beach grass.
Not sure about the random leaf despawning part, but the leaf block drops may be due to a syntax change needed in the loot tables file? See Promenade's recent change - https://github.com/DawnTeamMC/Promenade/commit/08bf9244b3f6d7b3c5e9a3a1491e195946d3d744

**Comment by AOCAWOL** [comment]
fabric 1.17 build was voided and will be re-evaluated at a later date.
