### ISSUE TITLE
Too many tropical fish in coral mangrove biome

### ISSUE THREAD

**Issue by MrKashew** [CorgiTaco/BYG#57]
> /kill @e[type=tropical_fish]
Killed 3595 entities

Drops frames from 100 to 1
lotsa fishies

**Comment by CorgiTaco** [comment]
MC Version? Forge or fabric?

**Comment by MrKashew** [comment]
Sorry - Fabric 1.16.1, byg-1.0.11.jar

**Comment by Linguardium** [comment]
despawn range is probably the issue due to:
https://github.com/CorgiTaco/BYG/blob/8ebe748ce43b46effe0488dbbbf01992d9fd0deb/src/main/java/voronoiaoc/byg/common/biomes/subbiomes/CoralMangroves.java#L66
fish are normally in WATER_AMBIENT, squids are in WATER_CREATURE

water ambient has a hard despawn limit of 64 blocks rather than the creature's 128 blocks but a higher spawn cap of 25 (ignored in initial chunk gen)

**Comment by CorgiTaco** [comment]
Expect the fix on Tuesday in 1.16.2

**Comment by CorgiTaco** [comment]
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3027087
