### ISSUE TITLE
[Bug]: Cannot craft chests with BYG Woods

### ISSUE THREAD

**Issue by Reshy** [CorgiTaco/BYG#600]
### Mod Version

 byg-1.3.5.jar

### Mod Loader

Forge

### Mod Loader Version

36.2.8 Forge

### What happened?

You cannot craft chests out of modded woods.
![2021-11-13_10 48 41](https://user-images.githubusercontent.com/2096384/141656314-b7ae9369-83dc-48e3-9ce7-6516a750783e.png)

### latest.log

No log involved.

**Comment by SirTwsted** [comment]
I can confirm this.  
I was just spawned in the middle of Ebony Woods Forest.  And no other tree's are around me at all for another 200+ blocks.
I can't store anything, because I can't create any chests with Ebony Planks.
Once my personal inventory is full, i'm kinda screwed now.  Enemies everywhere do to other mods, including super dark mod.
Can't even live in a cave until I level up enough to take care of these mobs, because I just cant store anything.

Also,  I have an achievement that is stuck and in the way of other items in the list,
because in order to complete, I have to collect wood, even though I have Ebony Logs & Planks.

 
![Screenshot_4](https://user-images.githubusercontent.com/15247713/141940847-29f837e2-9b2a-4c07-a382-4dbb2d2bcbf0.jpg)

As shown here:

![Screenshot_5](https://user-images.githubusercontent.com/15247713/141941122-5acf26b6-0fd0-4e42-953e-1e4633e82010.jpg)


🤷‍♂️

**Comment by saltyseadoggo** [comment]
Are you two using Quark? Quark disables the ability to make wooden chests out of wood types that aren't from vanilla, or a few mods with explicit support for Quark like those by AbnormalsMC or Team Aurora. This is a known issue. It can be solved by disabling Quark's variant chests feature.

**Comment by enduum** [comment]
Quark does this, possibly Charm as well. Made this datapack a while back as a workaround, it'll solve the issue regardless of what's causing it. It adds a copy of the vanilla recipe with a unique path so it won't be overwritten
[Quark_Vanilla_Chest_Fix_v1.zip](https://github.com/AOCAWOL/BYG/files/7572159/Quark_Vanilla_Chest_Fix_v1.zip)

**Comment by Reshy** [comment]
Thanks Enduum, I also made a bug report on Quark.

**Comment by Toma400** [comment]
You can always find one vanilla variant and use it with modded planks - I usually use spruce planks being 1/8 of recipe, and modded wood I wanted to use as 7/8 of recipe. Works really well.

**Comment by GMarty93** [comment]
> Quark does this, possibly Charm as well. Made this datapack a while back as a workaround, it'll solve the issue regardless of what's causing it. It adds a copy of the vanilla recipe with a unique path so it won't be overwritten
> [Quark_Vanilla_Chest_Fix_v1.zip](https://github.com/AOCAWOL/BYG/files/7572159/Quark_Vanilla_Chest_Fix_v1.zip)

Hi where do I drop this data pack?
