### ISSUE TITLE
[Bug]: at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:92)

### ISSUE THREAD

**Issue by TheButterbrotMan** [CorgiTaco/BYG#617]
### Mod Version

1.3.7

### Mod Loader

Fabric

### Mod Loader Version

0.12.12

### What happened?

Crashing at starting, probably a mod incompatibility

### latest.log

https://pastebin.com/YvwiyCZt

**Comment by orlouge** [comment]
I believe this is a compatibility issue between Terralith, TerraBlender and Better Nether (somehow), unrelated to BYG.
I made various attempts:
BCLib + BYG + Fabric API + Terralith + TerraBlender + BetterNether -> crash
BCLib + BYG + Fabric API + Terralith + TerraBlender -> ok
BCLib + BYG + Fabric API + TerraBlender + BetterNether -> ok
BCLib + Fabric API + Terralith + BetterNether -> ok

**Comment by CorgiTaco** [comment]
we need logs @orlouge

**Comment by TheButterbrotMan** [comment]
https://github.com/Glitchfiend/TerraBlender/issues/22

**Comment by TheButterbrotMan** [comment]
https://github.com/paulevsGitch/BetterNether/issues/503

**Comment by quiqueck** [comment]
Just a quick note (from the BetterNether Team). When this compatibility crash is fixed in BetterNether, the mods (TerraBlender and BetterNether) will still not work together. That means while there will be no crash, either BetterNether or TerraBlender Biomes will not be generated in the Nether (for example paulevsGitch/BetterNether#504). 

You'll find more info about that in the previously mentioned Thread over at the TerraBlender repo (Glitchfiend/TerraBlender#22).

**Comment by CorgiTaco** [comment]
seems out of BYG's control then
