### ISSUE TITLE
[Bug]: Overworld Dacite_Ridges Crashes World

### ISSUE THREAD

**Issue by ReapingOculus** [CorgiTaco/BYG#622]
### Mod Version

1.18.1

### Mod Loader

Forge

### Mod Loader Version

39.0.55

### What happened?

Every time I go into this biome the game crashes. I don't know if its a conflict with other mods or just a loading error.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/7916153/latest.log)
[crash-2022-01-21_13.27.34-server.txt](https://github.com/AOCAWOL/BYG/files/7916155/crash-2022-01-21_13.27.34-server.txt)

**Comment by CorgiTaco** [comment]
This may be another mod that adds world generation to biomes(modded included) you probably need to binary search your mod files until you dig it up, but I personally cannot reproduce the crash with BYG alone.

**Comment by ReapingOculus** [comment]
I figured out what mod was causing the issue. "Repurposed Structures" was spawning a structure in all the dacite ridge biomes causing the crash, as it seems. It's the only one that spawns something like a structure or biome that I was using aside from BYG. After I removed the mod, I flew around in creative for a couple minutes and it didn't crash. Guess they just don't play well together despite the mod only generating vanilla blocks. That little bit of information you gave, cut down the trouble shooting to 5 minutes instead of an hour, thank you!

**Comment by TelepathicGrunt** [comment]
@ReapingOculus uh, my mod doesnt not touch byg's stuff. All i do is add my structure to spawn in biomes. The crash you linked shows nothing to do with RS at all. See this part of the log https://paste.ee/p/6j7rJ

To me, this looks like twerkitmeal is the cause by trying to trigger bonemeal code on BYG's grass block.  Which then tries to spawn a grass placedfeature that has a biome filter placement which then crashes because it is not during worldgen.

I am very certain you will crash even without RS the moment you crouch on a BYG block and trigger twerkitmeal again. The issue is the byg grass block needs a custom grass placedfeature without the biome filter placement which should let it work with twerkitmeal again safely

**Comment by ReapingOculus** [comment]
OH that may it, I haven't tried it since removing that mod. That was causing me lag issues when testing it out and I have since removed it. I removed them both within that last couple hours and took a break, so it was more than likely that mod. I liked your mod so ill try reinstalling yours to test.

The issue was in the config, it happened whether I was crouching or not, since I couldn't get it to work properly I removed it. After reinstalling and testing @TelepathicGrunt it was definitely the twerkitmeal mod. Apologies about the misinformation and assumptions. Thank you for the quick response on that for testing out the compatibility!
