### ISSUE TITLE
Can not find a single biome in the nether

### ISSUE THREAD

**Issue by LGNNC** [CorgiTaco/BYG#633]
__**API/Modloader**__
Forge

__**Describe the bug**__
Can not find a single biome in the nether, I've explored so much of the nether and cant find one. I also tried finding one with natures compass but cannot find any that are listed on the wiki.
__**To Reproduce**__
Provide step by step instructions

**Expected [behavior**]
Just to fix that or tell me if its only for me thats happening that to.

**Logs**
Latest.log - https://paste.ee/p/q9Xvr

**Comment by CorgiTaco** [comment]
nether biomes do not exist on 1.18 at this time, they will be added once overworld biomes are are added

**Comment by LGNNC** [comment]
> nether biomes do not exist on 1.18 at this time, they will be added once overworld biomes are are added

Ok thank you for the information, i appreciate it.

**Comment by shaneknysh** [comment]
Before the biomes appear is there any way to grow Embur wood from a sapling, either in the nether or the overworld? We have tried to grow if in survival by giving a sapling and then planting it. 

Using bonemeal the sapling the sapling disappears but no tree is produced.  

If this doesn't work we will randomly pick a nether tree and gather that wood in place of the Embur instead of just cheating the wood in directly.

**Comment by shaneknysh** [comment]
Does this also affect the end biomes?

**Comment by CorgiTaco** [comment]
Nether biomes are now added for 1.18
