### ISSUE TITLE
[Bug]: Generation bug stone spheres

### ISSUE THREAD

**Issue by faeandsugar** [CorgiTaco/BYG#650]
### Mod Version

1.3.5.10

### Mod Loader

Forge

### Mod Loader Version

39.0.79

### What happened?

**Other mods installed that may be affecting this issue:**
Biomes O' Plenty
Terra Blender
Terraforged

**Issue:**
I'm experiencing a weird generation bug that only affects the different types of stone where they generate in huge spheres. I've encountered this generation bug in the Redwood Thicket and Twilight Valley.

I've used these mods in together before without issue, but it was on Minecraft 1.16.5

**Example image attached:**
![2022-02-25_10 58 39](https://user-images.githubusercontent.com/71529759/155756781-e899dc1b-7532-44a4-9ca6-019e1a470838.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8142957/latest.log)

**Comment by RedBeast1959** [comment]
Yeah, same thing happens to me in 1.18.1 version of Twilight Valley and Redwood Thicket. I thought It was intentional geographical feature of BYG until I saw stone sphere completely merged with tree
![2022-02-27_00 33 32](https://user-images.githubusercontent.com/100399264/155849056-f26c662d-1ec7-40b9-9b48-143457e86180.png)
![2022-02-27_00 45 53](https://user-images.githubusercontent.com/100399264/155849426-98ebe03b-0bc8-4c60-987b-d2ccee4525c9.png)
.

**Comment by CorgiTaco** [comment]
Fixed in 1.18.2
