### ISSUE TITLE
[Bug]: [GLITCH] My biome somehow changed from an Amaranth field to a shattered glacier.

### ISSUE THREAD

**Issue by theyorkster** [CorgiTaco/BYG#787]
### Minecraft Version

1.16.5

### BYG Version

1.3.5.

### Terrablender Version

n/a

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Bug Severity

Major

### What happened?

I am using BYG along with multiple MOD's in a custom modpack. One other MOD being Serene Season's which, as the title, adds seasons to the game..

I made stay in a beautiful Amaranth field and not until weeks later did i seem to have a problem with serene seasons mod where it just would not stop being winter so I deleted the mod but to my surprise, my biome was still consistently snowing and then i realized that my amaranth field is now picking up as a "shattered glacier." When I go into F3 it says that i am in a shattered glacier so somehow my biome has been permanently changed. I tried to create a forum with Serene Seasons as I assumed it was to do with them but they said that their mod does not cause such problems and that I must have taken another mod out with it which sadly is not true. 

Can you please help me fix this issue? I am not fond of this constant snowing lol. Please help!! Thank you so much! <3

### latest.log

[2022-05-30-3.log.gz](https://github.com/AOCAWOL/BYG/files/8819921/2022-05-30-3.log.gz)

**Comment by CorgiTaco** [comment]
If using Optifine: BYG & every other world generation mod in versions 1.16.2+ will break when Optifine shaders are active on forge. A workaround for this issue is to turn off shaders when loading your game/into a world and re-enable shaders AFTER entering your world.

If not using optifine:
Let's say....
The biome mods I have installed are BYG(Numerical ID's are 100 - 125), BOP(126 - 155), and Prehistoric Fauna(156 - 207).
I create a new world. the biome at 0, 0 is a PHF Hell's Creek.
Only the Biome numerical ID is saved to the chunk so... PHF Hell's Creek in this case is 157.
So biome numerical ID 157 is stored at 0, 0.
Alright... BYG just got an update and they added 3 new biomes. So what happens? Well....
The biome mods I have installed are now BYG(Numerical ID's are 100 - 128), BOP(129 - 158), and Prehistoric Fauna(159 - 210).
So now the biome at 0, 0 still has the numerical ID 157 but.... the ID's have shifted, now the biome at 0, 0 is a Biomes O Plenty Alps Biome.

I recommend that you use the latest version of your modloader as the issue has been fixed for sure.
Forge: http://files.minecraftforge.net/ or if that doesn't work, https://www.curseforge.com/minecraft/mc-mods/chocolate-fix/files
Fabric: https://fabricmc.net/use/ & https://www.curseforge.com/minecraft/mc-mods/fabric-api/files
