### ISSUE TITLE
[Crash]: potionstudios.byg.common.entity.boat.BYGBoatEntity

### ISSUE THREAD

**Issue by TheButterbrotMan** [CorgiTaco/BYG#798]
### Minecraft Version

1.18.2

### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-24

### Terrablender Version

TerraBlender-fabric-1.18.2-1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

0.14.6

### What happened?

Server crashes tonight.

### crash-log

https://bytebin.lucko.me/jKVxvZ6NJd

### latest.log

Dont have.

**Comment by SylvanusPC** [comment]
Also having this issue, except client side. I can provide another crash report:

https://pastebin.com/0ZR6eq7r

I have no idea what is going on with it. My version is Forge, so the issue exists on both. Version has not changed since it last worked to the best of my knowledge. I am going to try removing the mods I have added since then, see if that fixes anything.

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the latest version of BYG!
