### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by keluashi** [CorgiTaco/BYG#853]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.60

### What happened?

Crush when loading creating/loading world

### crash-log

[crash-2022-07-13_13.03.26-server.txt](https://github.com/AOCAWOL/BYG/files/9105022/crash-2022-07-13_13.03.26-server.txt)

### latest.log

[2022-07-13-2.log](https://github.com/AOCAWOL/BYG/files/9105030/2022-07-13-2.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by Stryckoeurz** [comment]
This seems to happen while trying to generate the Basalt Barreras , wich , from my testing doesn't happen in 1.18.2 1.4.1.
This somehow also bugs the structures being generated whilst a Basalt Barrera is generating , wich makes little sense to me... BYG also seems to have a hard time with TerraForged , but that may be cuz' of the 1.18 way to generate world/biomes.
Hope that can help the bug fixes.
The way to create these crashes is unreliable and i don't have the logs of mines.

**Comment by Dark-Thoughts** [comment]
@Stryckoeurz Did you mean to say Terralith? Because Terraforged is still on 1.16. Although I can't seem to make the former show up in the datapack menu at all anymore.

On Fabric I had these only at creating a world so far. By flying around I could find the biome dotted around without crashing (so far).

**Comment by Stryckoeurz** [comment]
No i meant terraforged , it has two alpha version in 1.18.2
It more or less doesn't correspond to the way it seems to generates in 1.16
tho
Hope that helps
Somehow it asks for the world to load in "safe world" but ends up crashing
when BYG is present , but no apparent reason other than JVM errors and the
Basalt Barrera Biome , still don't get what most of the error codes mean tho
It doesn't have issues with similar biomes (relativly similar to the basalt
barreras) so it may simply be related to many mods trying to overwrite
things at the same time ? (Structures , underground customization)
strangely it also seems to crash on BIOMOPLENTY only , but only when one is
near the spawn chunks , as doing the /locatebiom didn't crash the game last
time i checked , i also was able to generate world without the crash using
the past version (relative to the last version of 1.18.2 while i commented
on the github)...
I'm bad at JAVA so i probably won't be more pertinent than that...
If you want i can try to generate the bug again and send you the logs and
the crash infos later (currently 1:40 am).
Thanks for sending me an email and sorry i couldn't answer sooner...

Le lun. 18 juil. 2022 à 21:07, Dark Thoughts ***@***.***> a
écrit :

**Comment by Stryckoeurz** [comment]
> 
it was 2 am when i replied , that's why what's above barelly make sense

**Comment by Dark-Thoughts** [comment]
@Stryckoeurz It's okay. Thanks for "sending an email". ;)

To add to the topic: Still didn't had a crash while just flying around, generating terrain in an existing world. It also seems possible to "resume" the creation of a crashed world file, but I'm not sure if the biome generates properly in that case. So it does seem to have to do with the initial generation itself, rather than the biome generation in general? I'm not sure if there's even a difference in how the code handles it, maybe a chunk pregen mod could replicate the crash while within the world. The worldgen crashes for me seem to be all around 11-14 percent though. I'm not sure if that implies loaded spawn chunks or a specific early generation routine within the code.

**Comment by Shadowex3** [comment]
You're having a feature cycle order bug, same as #801 . If you install cyanide it'll give you a lot more detail in the logs telling you exactly which features are involved and even where they're called. For me getting rid of Ecologics, Biome Makeover, and a few others fixed it. For you it might be a different mod, but it's definitely caused by BYG and another biome mod conflicting in some way.

**Comment by Dark-Thoughts** [comment]
I can't do actual tests right now but I did have Ecologics installed as well.

**Comment by Shadowex3** [comment]
While reading up on Terralith and Terraforged I found some documentation of BYG being hardcoded to vanilla worldgen. What seems to be happening here is BYG having a feature cycle order error with mods that affect vanilla worldgen. I'm wondering if the two are related.

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the ***latest*** versions of all mods relating to world generation.
