### ISSUE TITLE
[Bug]: Black sand doesn't smelt into black stained glass as it should

### ISSUE THREAD

**Issue by demhadev** [CorgiTaco/BYG#877]
### Minecraft Version

1.19

### BYG Version

2.0.0.5

### Terrablender Version

2.0.0.117

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Bug Severity

Major

### What happened?

I'm pretty sure that black sand is supposed to smelt into black stained glass, since it says that in the recipe for black stained glass, but when you smelt it, it smelts into ordinary glass. I've isolated the mod and found that it smelts normally, so it seems as though a mod that's installed is interfering with the recipe. I've pasted the latest.log for the instance that isn't isolated.

https://user-images.githubusercontent.com/42255377/181080999-05c9b517-0526-4017-bce0-07c301c7bd7e.mov

<img width="343" alt="image" src="https://user-images.githubusercontent.com/42255377/181081126-e36e6eed-e534-47dc-b9a5-443d5a470ea3.png">

### latest.log

https://gist.github.com/demhadev/66ff4bc006c804c300902b3e4ff43e8b

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
All work for me on latest: 

https://user-images.githubusercontent.com/66983020/194813155-c0323544-43a3-4f84-a380-9fc38275dc71.mp4


*Seems the sand tag recipe for glass is controlling the white glass output in my video, probably can be fixed with [polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric).*
