### ISSUE TITLE
[Bug]: Error during the common_setup event phase

### ISSUE THREAD

**Issue by ponchisao326** [CorgiTaco/BYG#926]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Forge

### Mod Loader Version

43.1.1

### Bug Severity

Major

### What happened?

I have this mod in my server and it's working but when I try to enter to the MC it seems there's an error*

![image](https://user-images.githubusercontent.com/44710450/185906295-39a3e2af-1df6-49cf-94a9-7be4e15ea075.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9393746/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by justliliandev** [comment]
from what I can see, I think that you've updated to 1.19 recently, because the trades.json5 shouldn't have the id anymore.
if you haven't manually changed the \config\byg\trades.json5 config file in your .minecraft folder, you can try to delete it and it should recreate it automatically

**Comment by papillo12** [comment]
Delete the config folder

**Comment by wendall911** [comment]
If there is a crash or error in another mod, this can happen, as it prevents the configurations from being able to generate correctly. Not sure how to best handle this, as this kind of thing has long been solved in Forge, so not sure since you're rolling your own config here.

So the issue is that it looks like a BYG bug, when it is actually caused by another mod, just the errors from BYG are overpowering when this occurs.

**Comment by CorgiTaco** [comment]
Delete your trades config and let it regen
