### ISSUE TITLE
[Bug]: missing photo in guidebook

### ISSUE THREAD

**Issue by kittyLrose** [CorgiTaco/BYG#950]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.10

### Terrablender Version

2.0.1.125

### Mod Loader

Forge

### Mod Loader Version

43.1.13

### Bug Severity

Minor

### What happened?

There's no image for the White Mangrove Marshes in the biome section of the guidebook

![2022-09-03_19 12 37](https://user-images.githubusercontent.com/81041519/188290279-2e08d635-78ad-4312-b514-d4d841e826a2.png)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9483535/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by ishootzdaface** [comment]
I can confirm this bug on Fabric as well. 
Minecraft: 1.19.2
Fabric Loader: 0.14.9
Fabric API: 0.61.0
TerraBlender: 2.01.127
Oh The Biomes You'll Go: 2.0.0.11

I isolated exclusively BYG and the bug is still present. Additionally, if you click on the photo to read the page, it will crash to desktop on my version.
