### ISSUE TITLE
[Bug]: Therium Lanterns get waterlogged - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [CorgiTaco/BYG#968]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.11

### Terrablender Version

2.0.1.127

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### Bug Severity

Major

### What happened?

Therium Lanterns get waterlogged upon creation (in the End)

This is kinda awkward cause the water is flowing down when block update executed and it doenst look nice 

![2022-09-13_09 38 46](https://user-images.githubusercontent.com/97298005/189870242-c0b7336c-73ff-4bec-a5e1-f909aa2fc9e1.png)
![2022-09-13_09 42 01](https://user-images.githubusercontent.com/97298005/189870275-565af344-97af-4679-8756-f7f5b2bccc97.png)

### latest.log

[server latest.log](https://gist.github.com/SpigotDE/da62b826e38abdac2111bb036dbb3876)

[client latest.log](https://gist.github.com/SpigotDE/1b27bcbc5210fd547113b8ca6e65d705)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Gonna say this is either a registry mismatch or mod conflict because.... one of the properties on your therium lantern vs the one I see is that yours has two additional properties: `facing` & `on_wall`.


Here's what I see on my Therium Lantern's properties: 
![2022-10-09_21 59 18](https://user-images.githubusercontent.com/66983020/194801484-34aaba7d-902a-451f-848f-517cb817eaea.png)

Only has `hanging` & `waterlogged` properties. It also generates without water logging enabled.

**Comment by xR4YM0ND** [comment]
Probably from the mod "Lanterns Belong on Walls" https://www.curseforge.com/minecraft/mc-mods/lanterns-bow
