### ISSUE TITLE
[1.19][Crash]: New version of BYG crashes with Croptopia on Quilt when trying to create a new world or opening an existing save

### ISSUE THREAD

**Issue by SatDog92** [CorgiTaco/BYG#984]
### BYG Version

2.0.0.12

### Terrablender Version

2.0.1.128

### Mod Loader

Quilt

### Mod Loader Version

0.17.13

### What happened?

Apparently, when BYG is loaded with Croptopia, the game crashes as soon as you open an existing save or when you try to open the "Create New World" page. This does not happen on Fabric, only on Quilt. Previous 2.0.0.11 BYG version didn't have this issue, as i've used BYG with many other mods without game breaking issues, it only happens with this 2.0.0.12 one.

### crash-log

[crash-2022-10-10_13.15.35-client.txt](https://github.com/AOCAWOL/BYG/files/9745451/crash-2022-10-10_13.15.35-client.txt) when opening save.
[crash-2022-10-10_13.38.47-client.txt](https://github.com/AOCAWOL/BYG/files/9745601/crash-2022-10-10_13.38.47-client.txt) when trying to access the Create New World page.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9745756/latest.log)

### Did you isolate BYG?

I tried BYG alone (along with Croptopia to demonstrate the issue that didn't exist before)

**Comment by lospejos** [comment]
Also have the same issue.

**Comment by LambdAurora** [comment]
Hi!

I have looked a bit over the code of both projects.

I can confirm that this is not caused by BYG!
It is caused by Croptopia not using the proper APIs, leading to random incompatibilities.

If this behavior has not manifested before it's because BYG recently changed its mixins to using the APIs for making blocks strippable, in the old code BYG was making the map mutable without remaking it immutable, Croptopia on the other hand does something similar but keeps the immutability.
Before the bug might have been hidden by BYG applying its changes **after** Croptopia.

This issue should be reported to Croptopia instead.

**Comment by SatDog92** [comment]
Thank you for the detailed description of the issue, i'll head to the Croptopia's issues page for this instead.

**Comment by MysticcX** [comment]
Same issue but on Fabric not Quilt

**Comment by SatDog92** [comment]
> Same issue but on Fabric not Quilt

Most likely your issue on certain settings, can confirm Fabric doesn't make Croptopia crash with Byg.

**Comment by LambdAurora** [comment]
> Most likely your issue on certain settings, can confirm Fabric doesn't make Croptopia crash with Byg.

This issue occurs with specific load orders and mod sets, so this *could* happen on Fabric as well.
