### ISSUE TITLE
[1.19][Bug]: Normally compostable items in Fabric cannot be composted on Quilt

### ISSUE THREAD

**Issue by SatDog92** [CorgiTaco/BYG#987]
### BYG Version

2.0.0.12

### Terrablender Version

2.0.1.128

### Mod Loader

Quilt

### Mod Loader Version

0.17.5

### Bug Severity

Minor

### What happened?

All items in BYG that can be composted in Fabric cannot be composted when using Quilt. Even when using REI, the recipes do not appear at all (the issue also happens without REI and its dependencies).

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9779174/latest.log) (without REI)
[latest.log](https://github.com/AOCAWOL/BYG/files/9779152/latest.log) (with REI)

### Did you isolate BYG?

I tried BYG alone

**Comment by ItsMaddieNow** [comment]
This appears to be an issue with Quilt loading Fabric mods, I've pointed this out in their discord and they've created an issue on their git to fix it.

**Comment by ItsMaddieNow** [comment]
The Issue is here QuiltMC/quilt-standard-libraries#210

**Comment by EnnuiL** [comment]
Hello! I've determined that https://github.com/QuiltMC/quilt-standard-libraries/issues/210, while still problematic (and prevents the issue from being worked around with a data pack), it's not the cause of this issue.

The issue here is that instead of using Fabric API's content registry for adding items to the composter, mixins are being done instead, and yeah, this means that REA will cache the vanilla entries but it will clear anything else that has been added later because it wasn't added to its registry.

So, I recommend to use Fabric API's compost chance content registry on the Fabric side if possible, that way, we can safely bridge it through Quilted Fabric API's bridges. While in theory moving the compost registration to an earlier point can fix the issue, if not done carefully (like also making sure that the items are registered themselves before composter registration), it will instead worsen the issue and make it crash, so, yeah, I recommend using the established APIs for better mod compatibility
